### ISSUE TITLE
pcs login command fails

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-pcs-remote-monitoring-dotnet#78]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I am following the instructions at Getting Started / Setup section to proceed to a basic deployment but the pcs login command fails. The output is:

# Screenshot 

C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli>pcs login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C75HJNRLC to authenticate.
TypeError: Reflect.apply: argument is not an array or array-like object
   at ensureStackTrace (Unknown script code:234:9)
   at stackGetter (Unknown script code:244:9)
   at Logger.prototype.log (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\adal-node\lib\log.js:156:7)
   at Logger.prototype.error (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\adal-node\lib\log.js:168:3)
   at Logger.prototype.createError (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\adal-node\lib\log.js:202:3)
   at Anonymous function (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\adal-node\lib\util.js:130:7)
   at self.callback (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\request\request.js:186:7)
   at emitTwo (events.js:106:5)
   at emit (events.js:191:7)
   at Anonymous function (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\request\request.js:1163:5)
   at emitOne (events.js:96:5)
   at emit (events.js:188:7)
   at Anonymous function (C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli\node_modules\request\request.js:1085:7)
   at g (events.js:286:7)
   at emitNone (events.js:91:7)
   at emit (events.js:185:7)

C:\Users\mtheo\source\repos\azure-iot-pcs-remote-monitoring-dotnet\cli>pcs
Please run pcs login

# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
I am following the https://microsoft.com/devicelogin and I am "successfully" authenticated  with the provided code but I can't proceed to the next step "pcs" (basic deployment)

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by mtheolog** [comment]
I found the problem and resolved it. I uninstalled node chakra and installed the latest release of node.js. Thus I managed to proceed to a local deployment. Please close the issue.
